### ISSUE TITLE
Rename to posthtml-pug?

### ISSUE THREAD

**Issue by danielbayley** [posthtml/posthtml-pug#3]
See [here](https://github.com/pugjs/pug/issues/2184).

**Comment by michael-ciniawsky** [comment]
yes it's planned pug is currently in 2.0.0-alpha6 waiting for the release and dust around the rename settled.

**Comment by jescalan** [comment]
I'd recommend making a separate plugin for pug actually. The upgrade between the two is breaking, and the current stable version of jade will continue to live on npm, so it could be used if people want. This would just become more of an plugin for a legacy project, where more people would instead use the pug plugin.

**Comment by michael-ciniawsky** [comment]
@jescalan can you give a short overview of the breaking changes between jade and pug? I'm currently not up-to-date whats going on over there.

**Comment by jescalan** [comment]
I tried messing with it recently, and the API was very different. It's also not quite finished, some stuff isn't implemented, and nothing is documented. It's being worked on seemingly by just one person, who is currently a student and isn't going after it full time.

Makes me a little concerned for the future of jade tbh (I would much prefer a whitespace-sensitive posthtml parser combined with other packages), but my takeaway is basically that it's not going to get to a stable release any time soon, and when it does it will be a massively breaking release. The maintainer has confirmed in issue discussion that the current `jade` package will stay up and not go away, pug will essentially serve as a major version bump with a new name as well.

Because it's breaking, and because jade as it exists now will continue to exist, and some people will probably take a while to migrate over, it seems to me that the best solution is to simply wait until it's stable, then make a new `pug` adapter, so people can switch when they want, rather than having to deal with a breaking API update and a name change in an adapter they are already using.

I'll keep you up to date on this, as I check in periodically on pug, and when they are getting close to a stable release, would be happy to create or contribute to a plugin for it.

**Comment by michael-ciniawsky** [comment]
alright, then my knowledge is not as outdated as expected, i will make a repo and we can release it as beta aligned with pug for the time being

**Comment by michael-ciniawsky** [comment]
Indent based syntax with content transfomation is underway (posthtml-sml), jade and pug is just for legacy and during the fact of it's popularity in the node community. maybe a plugin like posthtml-consolidate (inspired by consolidate.js from express) would be a good idea to unify different templating languages and make it easier to interop.

**Comment by jescalan** [comment]
So I checked out `posthtml-sml` and it's looking nice! I just don't quite understand the little arrow symbols and filters for certain types of content like markdown and katex etc. Isn't the entire point of posthtml to reduce these types of mandatory integrations? I'd much rather use a plugin that just does whitespace-sensitive syntax only, then choose another plugin for rendering other languages (like [posthtml-md](https://github.com/jonathantneal/posthtml-md)) as needed.

As far as different templating languages, I wrote and maintain a better version of consolidate [here](https://github.com/jescalan/accord) for a project of mine, but I would actually like to start deprecating it. I feel like it's much better to pick and choose the features you want in a language and build it into what you are after, which I thought was the approach you guys were going for with posthtml. You have the expressions plugin, you can customize the delimiters. You have whitespace syntax if you want. You have plugins for transforming text and rendering markdown. Once you have a solid base of plugins, you should be able to build any other templating language directly out of posthtml plugins, which eliminates the need for a bunch of entirely separate libraries with their own parsers and set-in-stone features that developers must adhere to.

Imagine if, instead of offering compatibility with this or that templating language, you can just tell people to build the templating language that they want, using these available plugins. I mean, that turns posthtml from just another rendering engine to an absolute game changer when it comes to html transformation, the same way that postcss has for css. Notice that there's no postcss plugin for "sass", you can just build your own version of sass out of smaller modules like variables, mixins, nesting, etc.

**Comment by michael-ciniawsky** [comment]
> So I checked out posthtml-sml and it's looking nice! I just don't quite understand the little arrow symbols and filters for certain types of content like markdown and katex etc. Isn't the entire point of posthtml to reduce these types of mandatory integrations? I'd much rather use a plugin that just does whitespace-sensitive syntax only, then choose another plugin for rendering other languages (like posthtml-md) as needed.

That's a valid point, first priority should be a solid working syntax.

> As far as different templating languages, I wrote and maintain a better version of consolidate here for a project of mine, but I would actually like to start deprecating it.

Yep i know accord, i though of making a plugin with it but it also supports css, js, minifiers and that's not really suited for posthtml.

>  I feel like it's much better to pick and choose the features you want in a language and build it into what you are after, which I thought was the approach you guys were going for with posthtml. 

You're right with that assumption, i will try to give you an overview of what i currently planned to do on a bigger picture below.

You have the expressions plugin, you can customize the delimiters. You have whitespace syntax if you want. You have plugins for transforming text and rendering markdown.

locally i have a unfinished project(posthtml-ctx, or whatever), which is for transfroming content. Someone registers the the attrs name and/or 'prefix' inside the node content like in posthtml-sml and the module for the transformation.

``` html
<!DOCTYPE html>
<head></head>
<body>
 <article md>....</article>
 <article>↓| ........</article>
</body>
```

``` js
const ctx = require('posthtml-ctx')

posthtml([ctx({ attr: 'md', ctx: '↓|', require('markdown-it') })]).process(html)...
```

> Once you have a solid base of plugins, you should be able to build any other templating language directly out of posthtml plugins, which eliminates the need for a bunch of entirely separate libraries with their own parsers and set-in-stone features that developers must adhere to.

Help us out :). My goal is to create this solid base for PostHTML, so i can do future work completely PostHTML/PostCSS based. So everytime project specifics or someones personal preferences can opt-in and no need to switch entirely (like from e.g Jade to Haml, LESS to SASS or whatever).

**The overall picture**

**Configuration**

Autoload Setup from package.json/posthtml.config.js/posthtmltc.json/--config flag 

posthtml-load-config
|–posthtml-load-options
|–posthtml-load-plugins
|–posthtml-load-presets (Plugin Packs)

``` posthtml.config.js```
module.exports = {
  options: {
    sync: false
  },
  plugins: {
    'posthtml-plugin1': null,
    'posthtml-plugin2': {/* options */}
  },
  presets: {                                                    | // Extend preset with plugins at this pos 
   'posthtml-preset-mycompany': [ {plugin1: {}, plugin2: {}}, [1, 2] ]  
  }
}
```

**_Injection**_

e.g Imports, Modules, Extends, Metas, Scripts, Links, Assets

I would like to introduce @-rule syntax here as a convention

``` html
<!DOCTYPE html>
<head>
  @head
</head>
<body>
 <article>
   @img post.png
   @import post.html // plain import
 </article>
 <article>
   @img-lazy post2.png
   @module post2.html // import with posthtml subprocess for transfromation (e.g md)
 </article>
 @script index.js
</body>
```

My Current ideas are @img, @img-lazy, @font, @font-lazy, @svg, @style, @meta, @script, @script-async, @script-module, @head, @npm, @bower etc...

**\* Templating/Content***

posthtml-exp
posthtml-ctx,

Convention should be like in hbs
{{ content }}, {{ helper | content }},
{{{ content-escaped }}}, {{{ helper | content-escaped }}}

``` html```
<div class={{class}}>{{content}}</div>
```

Block level assigment is currently lacking e.g

``` html```
<div class={{class}}>
{{if content}}
  <p>{{content}}</p>
{{else}}
  <p>Hello!<p> 
</div>
```

posthtml-jsx for ouput and support in react based projects

**_Modularization**_

posthtml-classes
posthtml-postcss-classes

posthtml-postcss
posthtml-babel (I'm working on it)

``` html```
<style>Component CSS here<style>
<template name="">Component HTML here</template>
<script>Component JS here</script>
```

React/Polymer inspired for static sites etc.

**Comment by jescalan** [comment]
> Yep i know accord, i though of making a plugin with it but it also supports css, js, minifiers and that's not really suited for posthtml.

Doesn't matter, it doesn't bundle them as dependencies, so you don't have to use them. You can just use what you want out of accord 😁 

Really like the idea with the `ctx` plugin, this sounds great. That would also spawn a host of sub-plugins like the retext ones that I'm sure would be amazing!

> Help us out :)

More than willing to do that, just let me know where your priorities are at and the best way to jump in. I'm integrating posthtml into a very large project right now, which my company is running several production projects on, and which we plan to release to the public in the next month or so. I think it will see a pretty large chunk of publicity (which means you guys will as well) so I want to make sure everything is solid! I'm working full time on this right now, so I have bandwidth. If you want to chat more about this 1 on 1, I would be more than happy to, let me know and we can set something up.

> I would like to introduce @-rule syntax here as a convention

Any reason not to just use a normal element name or attribute? Why a new symbol?

All the rest of this sounds amazing. Excited to see where this project is going!

**Comment by michael-ciniawsky** [comment]
@-rule syntax should be interchangeable with a normal tag of course, i missed that

``` html
<div>
  @import file.html
</div> 
```

or 

``` html
<div>
  <import src="file.html"></import>
</div>
```

also as custom tags/snippets/mixins are an interesting option in my opinion

``` html
<row>
  <col-md></col-md>
<row>
<card></card>
```

you define them as componets like i mentioned before `<template name="row">....</template>` and they will then be replaced by posthtml.

**Comment by michael-ciniawsky** [comment]
> Any reason not to just use a normal element name or attribute? Why a new symbol?

Just for better visual overview, but yes that's subjective to some point :)

> More than willing to do that, just let me know where your priorities are at and the best way to jump in. I'm integrating posthtml into a very large project right now, which my company is running several production projects on, and which we plan to release to the public in the next month or so. I think it will see a pretty large chunk of publicity (which means you guys will as well) so I want to make sure everything is solid! I'm working full time on this right now, so I have bandwidth. If you want to chat more about this 1 on 1, I would be more than happy to, let me know and we can set something up.

👍  I have to finish a urgent but not really huge project at the moment, will took me at least 2 more days i guess.Then i have time to focus on this, I would also like to talk about all that in more detail and please share your thoughts and don't spare with critics, if arising.

**Comment by michael-ciniawsky** [comment]
>  If you want to chat more about this 1 on 1, I would be more than happy to, let me know and we can set something up.

@jescalan feel free to contact me on gitter when you find time
